name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_database.py

      - name: Build Docker image
        run: |
          docker build -t sharing-titanic .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag sharing-titanic ${{ secrets.DOCKER_USERNAME }}/sharing-titanic:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sharing-titanic:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: List files before deployment
        run: ls -R

      - name: SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Pulling the Docker image from Docker Hub..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/sharing-titanic:latest
            
            echo "Running the Docker container..."
            docker run -d -p 5000:5000 -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/sharing-titanic:latest
